### PR TITLE
Update Flux Pass Parameters to Stores

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. `applications/stores.js` can define a store as either a class or an array of a class and parameters
1. If just a class is passed it is initialized with no parameters
1. If an array is passed then the first element is assumed to be the class and any other elements are assumed to be the parameters

This example is how the matchMedia store can be initialized with queries and a default true query
```
var MatchMedia = require('synapse-common/store/match-media');

var Token = require('./store/token');
var User  = require('./store/user');

var params = {
    queries : {
        upToSmall  : '(max-width: 30em)', // up to 480px
        upToMedium : '(max-width: 48em)', // up to 768px
        upToLarge  : '(max-width: 64em)', // up to 1024px
        upToXLarge : '(max-width: 90em)' // up to 1440px
    },
    default : 'upToLarge'
};

module.exports = {
    MatchMedia : [MatchMedia, params],
    Token      : Token,
    User       : User
};
```

### CODE REVIEW

**Comment by paulstatezny** [comment]
:o:

**Comment by zpchavez** [comment]
I don't get it. Shouldn't the stores file just export the instantiated stores? What's the point of waiting to instantiate them in `flux.js`?

**Comment by areida** [comment]
On the server or you end up Flux object that was instantiated when you launched the server. The way it was set up before the stores would get instantiated when you did `require('./stores')` and then persist across the lifetime of the server.

**Comment by nearengine** [comment]
:+1:

**Pull request merged**
