### PR TITLE
IE < 11 gives blank page when connecting locally with IP

### PR DESCRIPTION
**Pull request by synbot**
## Description  

When connecting locally with IP and port, IE loads a blank page with console error.

## Details  

Console Error: {{expand and copy from the console, remove if not applicable}}  

```Flash Player >= 10.0.0 is required. Script 438: Object doesn't support property or method 'indexOf'
app.js, line 68 character 15```

### CODE REVIEW

**Comment by areida** [comment]
Shippable is failing due to some npm thing, I don't really get it. :pray:

**Comment by paulstatezny** [comment]
:pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Pull request merged**
