### PR TITLE
Make API requests to /api, not api subdomain

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. API requests go to `/api` on the current domain
1. Requests to `/api` are proxied to the correct API domain
1. `synapse-common` is updated to 1.4.0

### CODE REVIEW

**Comment by areida** [comment]
:warning: Blocked by synapsestudios/synapse-common#40

**Comment by areida** [comment]
:star:

**Comment by nearengine** [comment]
:pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Pull request merged**
