### PR TITLE
Server-side Rendering

### PR DESCRIPTION
**Pull request by synbot**
### ACs
1. Application can be rendered server-side
1. Flux data can be fetched intelligently
1. Flux data can be serialized and passed to the broswer
1. Flux data can be deserialzied and loaded into the stores
1. Implement APIStoreFactory from bodetree

### Notes
- I forked this branch and created a basic example of an isomorphic app that loads [github gists](https://github.com/areida/frontend-template)

### CODE REVIEW

**Comment by paulstatezny** [comment]
:two: minimum, not zero.

**Comment by paulstatezny** [comment]
:o:

**Comment by bobeagan** [comment]
:recycle:

**Comment by areida** [comment]
:boom: This was implementing as #105

**Pull request closed without merging**
