### PR TITLE
Strip out base components

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
We are stripping out all base components and moving them to [Synfrastructure](https://github.com/synapsestudios/synfrastructure/).

#### React
- [x] Remove buttons
- [x] Remove alerts and tooltips
- [x] Remove form components and mixins
- [x] Remove navigation components
- [x] Remove tab components
- [x] Clean up pattern library

#### SCSS
- [x] Remove _mixins (goes to synfrastructure)
- [x] Remove _extends
- [x] Remove component styles but keep file scaffolding
- [X] remove reset

### CODE REVIEW

**Comment by natestormer** [comment]
:star2:

**Comment by natestormer** [comment]
:o:

**Comment by natestormer** [comment]
:star2:

**Comment by kylecesmat** [comment]
:+1:

**Pull request merged**
