### PR TITLE
Reformat to airbnb standards

### PR DESCRIPTION
**Pull request by baohx2000**

### CODE REVIEW

**Comment by kylecesmat** [comment]
I'm seeing linting errors for the dev-server and other build files - mostly because they're not using es2015. Should we either ignore linting or update these files to es2015?

**Comment by baohx2000** [comment]
yeah…unfortunately dev-server doesn’t get babel-ified since it is run directly, so trying to convert it to es6 then running it just causes breakage (at least when I tried it).  And of course build files will have errors since they've been dumbed down to es5.  We should be able to specify certain folders & files not to be linted.  I can at least add that for dev-server.js

**Comment by kylecesmat** [comment]
It shouldn't need to get transpiled since it isn't running in a browser, but yeah I noticed that when I used some ES6 syntax with the latest Node, and didnt know why it was throwing errors?

I think it'd be preferable to use ES6 to keep everything modernized, but if that's a major rework for this PR we could just disable linting by wrapping the files w/ `/*eslint-disable */`

**Comment by baohx2000** [comment]
node's V8 engine doesn't implement es6 entirely yet, so I'll just disable those files from being linted for now.
FYI, I'm using `jscs` for linting since it has airbnb fixing mostly built in.
`npm install -g jscs` then `jscs .` inside the frontend-template folder.

**Comment by kylecesmat** [comment]
:+1:

**Comment by agerbens** [comment]
:+1: Nice

**Comment by chrisheninger** [comment]
Everything should be good to go now, if someone could pull the latest and double check that'd be swell.

**Comment by chrisheninger** [comment]
Everything should be good to go now, if someone could pull and double-check that would be swell.

**Pull request merged**
