### PR TITLE
app_settings.scss is being overwritten by synfrastructure

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. Changes to app_settings are interpreted by synfrastructure.

example: changing $row_width

### CODE REVIEW

**Comment by paulstatezny** [comment]
:interrobang: Shippable is complaining because Intl is defined in bootstrap.js but never used. Is it defined for a purpose there? Might need to ask @baohx2000 or @agerbens.

**Comment by baohx2000** [comment]
@paulstatezny That was removed in #92 ...still waiting on review/acceptance as it has been tested and is in use in beacon.

**Comment by kylecesmat** [comment]
Shippable crashing is unrelated to any of these changes, so we should be good to merge :star2:

**Comment by canfie1d** [comment]
:+1:

**Pull request merged**
