### PR TITLE
Update frontend-template to support server side rendering

### PR DESCRIPTION
**Pull request by synbot**
# Acceptance Criteria
* Initial requests render on the server then hand off to the app when it downloads
* IE < 9 Only gets the pre-rendered version of the app
* Search engine bots only get the pre-rendered version

# Issues
- [x] #106 - Remove unneeded files and file headers
- [x] #107 - Add new SSR dependencies and flux functions
- [x] #108 - Create server.js and associated webpack config and update homepage

### CODE REVIEW

**Comment by paulstatezny** [comment]
:pray:

**Comment by paulstatezny** [comment]
### Testing Instructions

1. Fire up the app
1. Navigate around the pattern library and make sure nothing is broken
1. Ensure that on first page load, the entire page loads instantly. (No loading required.) **Actually, I'm not sure you can test that here, since there's no API requests going on.**

**Comment by pcavagna** [comment]
:hand:

**Comment by areida** [comment]
:star:
### New Testing Instructions
1. Fire up app `npm start`
1. Load `localhost:9000`
 - Page should load instantly, no flashing or text changing
1. Open `application/ui/scss/dependencies/_colors.scss`
 - Change line 6 `$black : #000` to `$black: red`
 - Save file
 - Text on page should change to pinkish without reloading
1. Open `application/ui/pages/home.jsx`
 - Add `<p>Test</p>` after lilne 48
 - Save file
 - Text should appear on page without reload
1. Turn off javascript and reload
 - Page should load exactly as before

**Comment by paulstatezny** [comment]
:pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Pull request merged**
