### PR TITLE
Get Shippable working correctly

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. Shippable lints
1. Shippable builds without errors
1. Shippable runs tests without errors

### Tasks
- {{list developer tasks here}}

### Additional Notes
- {{list additional notes here, remove if not applicable}}

### CODE REVIEW

**Comment by bobeagan** [comment]
:o:

**Comment by zpchavez** [comment]
Running into this: https://github.com/Shippable/support/issues/1472

**Comment by zpchavez** [comment]
Running into this: https://github.com/Shippable/support/issues/1472

**Comment by zpchavez** [comment]
http://java.dzone.com/articles/running-javascript-tests-ci
Note to self: Try the solution here: https://github.com/karma-runner/karma/issues/1144

**Comment by zpchavez** [comment]
Got it! :m: :star: :gem: :trumpet:

**Comment by spruce-bruce** [comment]
:hand:

**Comment by spruce-bruce** [comment]
:+1:

**Comment by paulstatezny** [comment]
:clap: :clap: :confetti_ball: :tada: :dancers:

**Pull request merged**
