### PR TITLE
Update NPM Dependencies

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. Frontend template builds with no errors or console warnings

### Tasks
- Update NPM dependencies (except test-related dependencies)
- Replace autoprefixer-loader with postcss-loader + autoprefixer-core

### Notes
- Need to get designer help updating synfrastructure to 3.0.0

### CODE REVIEW

**Comment by bobeagan** [comment]
:o:

**Comment by kylecesmat** [comment]
:pray:

**Comment by kylecesmat** [comment]
:m:

**Comment by kylecesmat** [comment]
:star:

**Comment by zpchavez** [comment]
What's this failing build about? Can shippable even be trusted?

**Comment by zpchavez** [comment]
Seems fine. Don't know what shippable's complaining about. :star2:

**Comment by kylecesmat** [comment]
:pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Pull request merged**
