### PR TITLE
Use local webpack.js instead of shared global install

### PR DESCRIPTION
**Pull request by synbot**
Use local webpack.js instead of shared global install

## ACs
1. `npm start` works
1. `npm run webpack` works
1. `npm run dist` works
1. `npm test` works

### CODE REVIEW

**Comment by zpchavez** [comment]
:m: :star:

**Comment by paulstatezny** [comment]
:pray:

**Comment by pcavagna** [comment]
:hand:

**Comment by pcavagna** [comment]
:-1: 

Error when running npm commands in ACs

**Comment by agerbens** [comment]
@pcavagna Windows users still need to run `npm run windows` from the command line since it's a different set of commands. For instance, it uses `rmdir` instead of `rm` and `webpack.cmd` instead of `webpack`

**Comment by agerbens** [comment]
:star: Only change is to the `npm run windows` command.

**Comment by zpchavez** [comment]
:pray:

**Comment by zpchavez** [comment]
I tried.

**Comment by paulstatezny** [comment]
:pray: Shippable is failing, but I don't think it's our fault

**Comment by pcavagna** [comment]
:-1:

`npm start` doesn't work but using `rm -rf ./build && ./node_modules/webpack/bin/webpack.js && node webpack` works fine

**Comment by zpchavez** [comment]
From `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart frontend-template@0.0.0
6 info start frontend-template@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info frontend-template@0.0.0 Failed to exec start script
9 verbose stack Error: frontend-template@0.0.0 start: `rm -rf ./build && ./node_modules/webpack/bin/webpack.js && node webpack`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid frontend-template@0.0.0
11 verbose cwd c:\Users\Synapse\Documents\GitHub\frontend-template
12 error Windows_NT 6.1.7601
13 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error frontend-template@0.0.0 start: `rm -rf ./build && ./node_modules/webpack/bin/webpack.js && node webpack`
17 error Exit status 1
18 error Failed at the frontend-template@0.0.0 start script 'rm -rf ./build && ./node_modules/webpack/bin/webpack.js && node webpack'.
18 error This is most likely a problem with the frontend-template package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     rm -rf ./build && ./node_modules/webpack/bin/webpack.js && node webpack
18 error You can get their info via:
18 error     npm owner ls frontend-template
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by bobeagan** [comment]
:o: i'm taking over this one to get it working properly for windows users too

**Comment by zpchavez** [comment]
Whatever happened with this? :recycle:

**Comment by zpchavez** [comment]
¯\_(ツ)_/¯ :star:

**Comment by paulstatezny** [comment]
Do we really need sourcemaps on for `__tests__/webpack.config.js`?

**Comment by paulstatezny** [comment]
:pray:

**Comment by dmmcinty** [comment]
:hand:

**Comment by dmmcinty** [comment]
:+1:

**Comment by zpchavez** [comment]
Guess I'll fix those jshint errors.

**Pull request merged**
