### PR TITLE
Include favicons and css files with media.js file

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. `media.js` is required in the bootstrap file
1. `media.js` requires all the static media files for the app
1. Favicons are loaded with the `file-loader`, not `image-loader`

### CODE REVIEW

**Comment by areida** [comment]
:pray:

**Comment by paulstatezny** [comment]
:pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Pull request merged**
