### PR TITLE
New install script

### PR DESCRIPTION
**Pull request by synbot**
No one is using the current install script. For this I blame myself. We should replace it with one that is easier to use.

### Acceptance Criteria
1. `initialize.sh` is gone
1. `clone.sh` is here
1. `QA_HOST=domain.com ./clone.sh [destination] [project-name]` will create a copy of the frontend template at `destination` configured to connect to `[project-name].vm`, `[project-name]-qa.domain.com`, and `[project-name].com` in dev, QA, and production configs

### CODE REVIEW

**Comment by bobeagan** [comment]
:o:

**Comment by areida** [comment]
:star:

**Comment by paulstatezny** [comment]
:pray:

**Comment by paulstatezny** [comment]
### Testing Instructions

Follow the new instructions in the README.md to make a new (fake) project. (Just call it `foo` or `test` or something.)

Make sure that project can build and run.

**Comment by nearengine** [comment]
:+1:

**Pull request merged**
