### PR TITLE
Add /media folder

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. /media folder is added to template to organize assets
2. Webpack-image-loader loads in required images, Base64 encodes & optimizes them

### CODE REVIEW

**Comment by natestormer** [comment]
:+1:

**Comment by bobeagan** [comment]
:-1: pretty sure this also needs an update to webpack or these assets won't be included in the build

**Comment by kylecesmat** [comment]
:star2:  We added an image-loader to handle loading images by requiring them in as variables.

**Comment by kylecesmat** [comment]
Actually, this should be looked over by a dev :star:

**Comment by paulstatezny** [comment]
:pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Pull request merged**
